In [17]:
import numpy as np
import pandas as pd

np.random.seed(50)

n = 200 #this will represent the randomized factors for attorney's I'll randomize below

experience = np.random.randint(0, 31, size=n)
win_ratio = np.random.uniform(0.2, 0.9, size=n) #ratio strictly between 0.2-0.9
education_level = np.random.choice(['JSD', 'LLM', 'JD'], size=n, p=[0.1, 0.3, 0.6])

education_factored = np.array([1.0 if ed == 'JSD' else 0.85 if ed == 'LLM' else 0.7 for ed in education_level])
experience_factored = experience / 30

score = 0.5 * experience_factored + 0.3 * win_ratio + 0.2 * education_factored

case_result = np.where(score > 0.6, 1, 0)
print("Scores:", score)
print("Case Results:", case_result)

Scores: [0.62413433 0.28660957 0.50127866 0.49704152 0.27164179 0.83815672
 0.27846227 0.43566134 0.47358646 0.37266851 0.76045494 0.46047889
 0.2894952  0.3632651  0.76237809 0.46539602 0.52658917 0.46621373
 0.58304383 0.32711284 0.85086997 0.68474737 0.70750202 0.84078431
 0.32258034 0.59085896 0.48960273 0.59081234 0.71031201 0.60510991
 0.49931901 0.32447516 0.82593638 0.67445306 0.49875584 0.58830134
 0.29291962 0.47857335 0.88143463 0.3886898  0.51579347 0.58221491
 0.79250655 0.84638962 0.56551325 0.42653304 0.54241812 0.40593496
 0.42891914 0.34323427 0.53981355 0.53793016 0.5269512  0.57094739
 0.20553315 0.86496815 0.71906306 0.77021209 0.29634469 0.51349308
 0.86907184 0.70078072 0.44190319 0.64887359 0.86839104 0.64515431
 0.75135922 0.57020977 0.76001951 0.49349845 0.36755457 0.38451602
 0.38499781 0.32837838 0.83451184 0.51244585 0.34335226 0.63843474
 0.57810317 0.79742928 0.417163   0.70731248 0.31640967 0.71151705
 0.49168397 0.77592708 0.7144023  0.44809862 0.43891232 0.77529723
 0.36305052 0.69298364 0.65552308 0.7814582  0.45648821 0.76391036
 0.37238866 0.35297893 0.36257909 0.5907863  0.33003206 0.49728965
 0.68941699 0.45949094 0.37207311 0.75583079 0.52719009 0.55284763
 0.27582639 0.28443329 0.43602557 0.87629311 0.86236881 0.52198428
 0.43433129 0.35015233 0.49504216 0.71604157 0.51223309 0.74080093
 0.67297248 0.71585049 0.47060434 0.5384727  0.54488058 0.80220088
 0.6361865  0.6302885  0.92085891 0.76327044 0.48302716 0.42134985
 0.43649741 0.59995679 0.58877212 0.58444285 0.57052903 0.66718827
 0.4514973  0.55729953 0.55176194 0.69216304 0.69532724 0.79188352
 0.52894121 0.49433123 0.34306967 0.63823714 0.37419076 0.32706468
 0.36725898 0.55415831 0.40386933 0.25397796 0.50834296 0.85298205
 0.55888452 0.64887573 0.33381449 0.83140243 0.72057199 0.74948115
 0.65143629 0.74780566 0.32274626 0.67592829 0.86748888 0.59645764
 0.73321031 0.64079437 0.58390313 0.52112091 0.71699643 0.40485123
 0.56590045 0.80241087 0.78044485 0.55564337 0.43748556 0.80954406
 0.91954376 0.41320295 0.681553   0.2938667  0.8255809  0.63545096
 0.50190524 0.65881515 0.66623906 0.6082635  0.70520695 0.71127393
 0.76727706 0.324693   0.61910499 0.29555414 0.3167176  0.57838569
 0.57338566 0.33798147]
Case Results: [1 0 0 0 0 1 0 0 0 0 1 0 0 0 1 0 0 0 0 0 1 1 1 1 0 0 0 0 1 1 0 0 1 1 0 0 0
 0 1 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 1 1 1 0 0 1 1 0 1 1 1 1 0 1 0 0 0 0 0
 1 0 0 1 0 1 0 1 0 1 0 1 1 0 0 1 0 1 1 1 0 1 0 0 0 0 0 0 1 0 0 1 0 0 0 0 0
 1 1 0 0 0 0 1 0 1 1 1 0 0 0 1 1 1 1 1 0 0 0 0 0 0 0 1 0 0 0 1 1 1 0 0 0 1
 0 0 0 0 0 0 0 1 0 1 0 1 1 1 1 1 0 1 1 0 1 1 0 0 1 0 0 1 1 0 0 1 1 0 1 0 1
 1 0 1 1 1 1 1 1 0 1 0 0 0 0 0]

In [18]:
dataframe = pd.DataFrame({
    'Experience_Years': experience,
    'Win_Loss_Ratio': win_ratio.round(2),
    'Education_Level': education_level,
    'Weighted_Score': score.round(2),
    'Case_Results': case_result
})
dataframe.head()

,Experience_Years,Win_Loss_Ratio,Education_Level,Weighted_Score,Case_Results
0,16,0.72,JD,0.62,1
1,0,0.49,JD,0.29,0
2,11,0.59,JD,0.50,0
3,13,0.37,LLM,0.50,0
4,1,0.38,JD,0.27,0

In [19]:
dataframe.to_csv('attorney_case_dataset.csv', index=False)